### ISSUE TITLE
mac issues

### ISSUE THREAD

**Issue by crisward** [parro-it/libui-node#10]
May need to update your readme....

* I needed to manually download the sub-module, not sure why but git wouldn't pull it
* needs making clear you need node v6
* perhaps note you can install cmake with homebrew on mac `brew install cmake`
* After all that, the gui still didn't appear on mac...? (running npm start)

Love to see this working so any feedback would be nice, thanks.

**Comment by PaulBGD** [comment]
Yeah it definitely needs to be made clear that you need node v6,

**Comment by jjrv** [comment]
Up to commit c9a75e2759f4eb291cbb3c9bec18b8419d5bdefe it works on Node.js versions all the way from 0.10.

Additionally, on OS X 10.8 I need to comment out this line: https://github.com/parro-it/libui-node/blob/c9a75e2759f4eb291cbb3c9bec18b8419d5bdefe/example.js#L15

**Comment by jjrv** [comment]
@parro-it The earlier Node.js versions don't like ES6 features like let and const. I'd recommend transpiling to ES5. Babel works but I'd choose TypeScript, nbind will later auto-generate typings which then propagate to users of this project as well.

**Comment by parro-it** [comment]
@crisward I add missing details in readme to install cmake and update git submodule.

Regarding ES6 code, the only javascript file is `index.js`. It's so simple I prefer to avoid ES6 syntax at all to avoid traspilation. I will edit it later today, shorten the "engine" requirements on pkg.json and add node versions to travis.
The code in examples folder it's more heavy on new js syntax. 

I think I'll transpile only that, maybe doing it a module with a packahe.json and it's own devdeps. 
The `utils.js` file there is the core of an higher level API I'll move however to another repo...

@jjrv I definitely want to provide TypeScript type checking, but only if that doesn't cause problems to normal JS user. I never used TypeScript, so really I don't know...

**Comment by parro-it** [comment]
I also got problem on OSX running example. I restored the simpler example @jjrv was using. That work for me... I will investigate further this evening, meanwhile I add a note on readme for OSX users

**Comment by parro-it** [comment]
I manage to make the example running on OSX 10.10. 
There are two issues here:

1) Apparently multiline entries has some problem. I  temporary replaced them with normal entry to make it work 
2) The `startloop` method in [index.js](https://github.com/parro-it/libui-node/blob/master/index.js) does not work in OSX. I replaced that with `libui.Ui.main()` and it work. The problem with `libui.Ui.main()`is that it block the `Node.js` event loop, so I've to find a way to revert this change...

**Comment by jjrv** [comment]
Looks like the `startLoop` method is basically polling UI events. Maybe the UI needs to rather run in a separate thread? :/

**Comment by parro-it** [comment]
@jjrv no, there is no need for multithreading. I found about uiMainStep reading [these issues](https://github.com/andlabs/libui/search?q=uiMainStep&type=Issues&utf8=%E2%9C%93).
If I've understood correctly, `uiMainStep` run one event from `libui` event loop and then returns. I continuously call it in a setImmediate call, so it should run one `libui` event per node tick.

It's working on Linux, so I don't know...

**Comment by parro-it** [comment]
Today I was able to workaround the loop problem on OSX 10.10 by comment these two lines on [main.m](https://github.com/andlabs/libui/blob/master/darwin/main.m#L169) on `libui`. 
It appear there is some problem on uiMainStep function. They are tracking progress on [this issue](https://github.com/andlabs/libui/issues/95).

As a temporary workaround, I will make `startLoop` method call `uiMain` function instead of `uiMainStep` in OSX.

**Comment by crisward** [comment]
Thanks for the update...

**Comment by parro-it** [comment]
You're welcome! I will report here further progress (hoping soon)

**Comment by parro-it** [comment]
All macOS issues seems solved, I close the issue.
