### ISSUE TITLE
Remove OS specific ternary

### ISSUE THREAD

**Issue by TheJaredWilcurt** [parro-it/libui-node#107]
In the Control Gallery example you have a line like this:

```js
onDarwin ? entry(searchText) : searchEntry(searchText),
```

It makes more sense to me, to just move that logic into the definition of `searchEntry`.

```js
const entry = mkControl(libui.UiEntry, {
    readOnly: false,
    enabled: true,
    text: '',
    visible: true,
    onChanged: EventHandler
});

let searchEntry;

if (os.platform === 'darwin') {
    searchEntry = mkControl(libui.UiEntry, {
        readOnly: false,
        enabled: true,
        text: '',
        visible: true,
        onChanged: EventHandler
    });
} else {
    searchEntry = mkControl(libui.UiSearchEntry, {
        readOnly: false,
        enabled: true,
        text: '',
        visible: true,
        onChanged: EventHandler
    });
}
```

This way the API is cleaner for users, also it allows for improvements in the future. I assume this ternary exists because `searchEntry` is not available on OSX, so it just uses the `entry` fallback. If this functionality becomes available in the future of that OS, then user's will inherit it automatically, and until then they will get a graceful degradation.

I'm just using this one piece of code as an example, but I think this should be considered more broadly as a pattern to reduce the complexity of the cross-platform nature of the API.

I've also been looking at the code base for about 30 minutes, so I welcome feedback/discussion on this suggestion.

**Comment by mischnic** [comment]
I don't think that check is needed anymore. 
Original bug report: https://github.com/parro-it/libui-node/issues/9#issuecomment-225481658
Bug was solved in libui: https://github.com/andlabs/libui/issues/132

**Comment by parro-it** [comment]
@TheJaredWilcurt would you mind doing a PR that remove the check altogether?

**Comment by parro-it** [comment]
@TheJaredWilcurt any chance?
