### ISSUE TITLE
How to build an example app into binary executable file?

### ISSUE THREAD

**Issue by jiewuza** [parro-it/libui-node#108]
I am quite new to use node for desktop app.
I clone the project, and run `npm run start-np` successfully.
Now I want to build this example into a binary executable file, 
and `npm run build` does not work, 
and I cannot find the doc.

**Comment by parro-it** [comment]
It should be possible using electron-builder, but I still had not the time to test it out...
You can find some ongoing discussion here: https://github.com/kusti8/proton-native/issues/43

**Comment by mischnic** [comment]
After #2903 gets fixed. It should work.

**Comment by mischnic** [comment]
The fix is released as electron-builder 20.15.0

**Comment by ghost** [comment]
If someone could post steps for example app into exe that would be very helpful
