### ISSUE TITLE
How to center window and make give it focus on macOS?

### ISSUE THREAD

**Issue by NetOperatorWibby** [parro-it/libui-node#109]
I'm looking through the examples for examples of such but have not found it.

Thanks for this incredible library btw, native desktop apps are within my reach now.

**Comment by parro-it** [comment]
You have to pack your command in an app folder.
This will be done automatically using proton-packager in future release.

You can see an example here:

https://github.com/parro-it/libui-node/blob/master/examples/ControlGallery.app/Contents/MacOS/ControlGallery

But until we solve #67, remember to change the paths there to your own.

> Thanks for this incredible library btw, native desktop apps are within my reach now.

Thank you! You make my day!

**Comment by NetOperatorWibby** [comment]
Ah, is it possible for what I want to be achieved when working via Terminal?

**Comment by parro-it** [comment]
> Ah, is it possible for what I want to be achieved when working via Terminal?

Yes, you can use 
```bash
$ open <path/to/your/folder.app>
```

And that should open your app, focused, from the terminal.

**Comment by mischnic** [comment]
> This will be done automatically using proton-packager in future release.

*electron-builder*. Once https://github.com/electron-userland/electron-builder/issues/2903 is resolved.

**Comment by parro-it** [comment]
Oh yes, sorry
