### ISSUE TITLE
Change Window title/size/menu

### ISSUE THREAD

**Issue by PaulBGD** [parro-it/libui-node#11]
Currently there's no way to change a Window's title, size, or if it has a menu without creating a new one.

**Comment by PaulBGD** [comment]
As well there's no way to tell if the Window's size has changed.

**Comment by parro-it** [comment]
These features are missing from `libui` at the moment. 
Since they are really basic features, I think they are already on @andlabs radar.
I don't think if he link if we open issues on its repo, there are a lot of these simple think lacking by now.
@andlabs what do you prefer about?

Anyway, I reopen this issue as a placeholder to implements these API when/if they will come...

**Comment by andlabs** [comment]
Changing a title is there; uiWindowSetTitle().

Not sure what you would do on window size change, since the window's child is automatically resized accordingly...?

The menu system is a mess and needs to be replaced.

**Comment by parro-it** [comment]
@andlabs I mean to ask you how do you prefer to manage these kind of issues (about missing parts of API you'll probably implement soon)...

Some example pf missing pieces I've found so far while developing node bindings:

* Setting size/position of windows
* Setting/getting minimization/maximization state of windows
* Getting/Setting value of date/datetime

and so on...
I guess these are things you'll add anyway, someone are written in your TODO file
so I ask you if you prefer that I open issues on `libui` repo (or maybe on issue only with a list)

**Comment by parro-it** [comment]
Regarding the title it's my fault, I miss to implement this property in `libui-node`. I'll add it soon...

**Comment by andlabs** [comment]
Yes, please use issues on the libui repo.

**Comment by parro-it** [comment]
I've split this issue: #13 #14 #15 #16 #17, I close this issue and will track on these....
