### ISSUE TITLE
REQUEST: Shortcut support in menubar

### ISSUE THREAD

**Issue by NetOperatorWibby** [parro-it/libui-node#111]
_Example_

![ss 2018-05-20 at 11 19 33 pm](https://user-images.githubusercontent.com/1288356/40290583-68a59ab4-5c84-11e8-90b9-ea684cf6037c.png)

I did some digging in the `libui` repo and saw that shortcuts were in the "TODO" list.

**Comment by NetOperatorWibby** [comment]
![ss 2018-05-20 at 11 41 41 pm](https://user-images.githubusercontent.com/1288356/40290968-6c9025ce-5c87-11e8-9a88-79015d97371f.png)

Manually spacing doesn't quite work, as you can see with **Mark All As Read**.

**Comment by mischnic** [comment]
> I did some digging in the libui repo and saw that shortcuts were in the "TODO" list.

Correct, we have to wait for libui to implement it.

> Manually spacing doesn't quite work, as you can see with Mark All As Read.

What do you mean by "Manual spacing"?

**Comment by parro-it** [comment]
> What do you mean by "Manual spacing"?

I think she tried to manually insert shortcuts description in menu item, aligning them to right by inserting spaces in the item menu caption.
