### ISSUE TITLE
Compile error Windows 10

### ISSUE THREAD

**Issue by mischnic** [parro-it/libui-node#114]
Windows 10

` Cannot open include file: 'core.h': No such file or directory (compiling source file ..\src\Color.cc)`

```json
{
  "name": "test",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node_modules/.bin/babel-node index.js",
    "build": "node_modules/.bin/babel index.js -d bin/",
    "pack": "electron-builder --dir",
    "dist": "electron-builder"
  },
  "dependencies": {
    "proton-native": "latest"
  },
  "devDependencies": {
    "electron-builder": "latest",
    "babel-cli": "latest",
    "babel-preset-env": "latest",
    "babel-preset-stage-0": "latest",
    "babel-preset-react": "latest"
  },
  "build": {
    "protonNodeVersion": "current",
    "mac": {
      "identity": null
    }
  }
}

```

<summary>Log:</summary>
<details>
<code><pre>
C:\Users\nikla\Desktop\DEV\test>npm i

> libui-node@0.2.0 install C:\Users\nikla\Desktop\DEV\test\node_modules\libui-node
> libui-download && autogypi && npm run build

Downloaded zip: C:\Users\nikla\.libui\libui-shared-windows-x64-alpha3.5-master-002.tar.gz
Libui binaries extracted to: C:\Users\nikla\Desktop\DEV\test\node_modules\libui-node

> libui-node@0.2.0 build C:\Users\nikla\Desktop\DEV\test\node_modules\libui-node
> node-gyp configure build

C:\Users\nikla\Desktop\DEV\test\node_modules\libui-node>if not defined npm_config_node_gyp (node "C:\Users\nikla\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure build )  else (node "C:\Users\nikla\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" configure build )
Warning: Missing input files:
C:\Users\nikla\Desktop\DEV\test\node_modules\libui-node\build\Release\nbind.node
Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu ermöglichen, müssen Sie den Schalter "/m" hinzufügen.
  Copying ../nbind/src/symbols.txt to Release\obj\nbind\\symbols.txt
          1 Datei(en) kopiert.
  common.cc
  reflect.cc
  Color.cc
  EventLoop.cc
C:\Users\nikla\.node-gyp\10.2.0\include\node\node.h(53): fatal error C1083: Cannot open include file: 'core.h': No such file or directory (compiling source file ..\src\Color.cc) [C:\Users\nikla\Desktop\DEV\test\node_modules\libui-node\
build\nbind.vcxproj]
C:\Users\nikla\.node-gyp\10.2.0\include\node\node.h(53): fatal error C1083: Cannot open include file: 'core.h': No such file or directory (compiling source file ..\..\nbind\src\reflect.cc) [C:\Users\nikla\Desktop\DEV\test\node_modules\
libui-node\build\nbind.vcxproj]
C:\Users\nikla\.node-gyp\10.2.0\include\node\node.h(53): fatal error C1083: Cannot open include file: 'core.h': No such file or directory (compiling source file ..\..\nbind\src\common.cc) [C:\Users\nikla\Desktop\DEV\test\node_modules\l
ibui-node\build\nbind.vcxproj]
  Point.cc
  PointDouble.cc
  Size.cc
C:\Users\nikla\.node-gyp\10.2.0\include\node\node.h(53): fatal error C1083: Cannot open include file: 'core.h': No such file or directory (compiling source file ..\src\Point.cc) [C:\Users\nikla\Desktop\DEV\test\node_modules\libui-node\
build\nbind.vcxproj]
  SizeDouble.cc
C:\Users\nikla\.node-gyp\10.2.0\include\node\node.h(53): fatal error C1083: Cannot open include file: 'core.h': No such file or directory (compiling source file ..\src\Size.cc) [C:\Users\nikla\Desktop\DEV\test\node_modules\libui-node\b
uild\nbind.vcxproj]
C:\Users\nikla\.node-gyp\10.2.0\include\node\node.h(53): fatal error C1083: Cannot open include file: 'core.h': No such file or directory (compiling source file ..\src\PointDouble.cc) [C:\Users\nikla\Desktop\DEV\test\node_modules\libui
-node\build\nbind.vcxproj]
  timer-common.cc
  Ui.cc
C:\Users\nikla\.node-gyp\10.2.0\include\node\node.h(53): fatal error C1083: Cannot open include file: 'core.h': No such file or directory (compiling source file ..\src\SizeDouble.cc) [C:\Users\nikla\Desktop\DEV\test\node_modules\libui-
node\build\nbind.vcxproj]
  UiBox.cc
C:\Users\nikla\.node-gyp\10.2.0\include\node\node.h(53): fatal error C1083: Cannot open include file: 'core.h': No such file or directory (compiling source file ..\src\timer-common.cc) [C:\Users\nikla\Desktop\DEV\test\node_modules\libu
i-node\build\nbind.vcxproj]
C:\Users\nikla\.node-gyp\10.2.0\include\node\node.h(53): fatal error C1083: Cannot open include file: 'core.h': No such file or directory (compiling source file ..\src\Ui.cc) [C:\Users\nikla\Desktop\DEV\test\node_modules\libui-node\bui
ld\nbind.vcxproj]
  UiButton.cc
  UiCheckbox.cc
C:\Users\nikla\.node-gyp\10.2.0\include\node\node.h(53): fatal error C1083: Cannot open include file: 'core.h': No such file or directory (compiling source file ..\src\UiBox.cc) [C:\Users\nikla\Desktop\DEV\test\node_modules\libui-node\
build\nbind.vcxproj]
  UiColorButton.cc
C:\Users\nikla\.node-gyp\10.2.0\include\node\node.h(53): fatal error C1083: Cannot open include file: 'core.h': No such file or directory (compiling source file ..\src\UiButton.cc) [C:\Users\nikla\Desktop\DEV\test\node_modules\libui-no
de\build\nbind.vcxproj]
C:\Users\nikla\.node-gyp\10.2.0\include\node\node.h(53): fatal error C1083: Cannot open include file: 'core.h': No such file or directory (compiling source file ..\src\UiCheckbox.cc) [C:\Users\nikla\Desktop\DEV\test\node_modules\libui-
node\build\nbind.vcxproj]
  UiCombobox.cc
  UiControl.cc
C:\Users\nikla\.node-gyp\10.2.0\include\node\node.h(53): fatal error C1083: Cannot open include file: 'core.h': No such file or directory (compiling source file ..\src\UiColorButton.cc) [C:\Users\nikla\Desktop\DEV\test\node_modules\lib
ui-node\build\nbind.vcxproj]
  UiDateTimePicker.cc
C:\Users\nikla\.node-gyp\10.2.0\include\node\node.h(53): fatal error C1083: Cannot open include file: 'core.h': No such file or directory (compiling source file ..\src\UiCombobox.cc) [C:\Users\nikla\Desktop\DEV\test\node_modules\libui-
node\build\nbind.vcxproj]
  UiEditableCombobox.cc
C:\Users\nikla\.node-gyp\10.2.0\include\node\node.h(53): fatal error C1083: Cannot open include file: 'core.h': No such file or directory (compiling source file ..\src\UiControl.cc) [C:\Users\nikla\Desktop\DEV\test\node_modules\libui-n
ode\build\nbind.vcxproj]
  UiEntry.cc
C:\Users\nikla\.node-gyp\10.2.0\include\node\node.h(53): fatal error C1083: Cannot open include file: 'core.h': No such file or directory (compiling source file ..\src\UiDateTimePicker.cc) [C:\Users\nikla\Desktop\DEV\test\node_modules\
libui-node\build\nbind.vcxproj]
  UiFontButton.cc
C:\Users\nikla\.node-gyp\10.2.0\include\node\node.h(53): fatal error C1083: Cannot open include file: 'core.h': No such file or directory (compiling source file ..\src\UiEditableCombobox.cc) [C:\Users\nikla\Desktop\DEV\test\node_module
s\libui-node\build\nbind.vcxproj]
  UiForm.cc
C:\Users\nikla\.node-gyp\10.2.0\include\node\node.h(53): fatal error C1083: Cannot open include file: 'core.h': No such file or directory (compiling source file ..\src\UiEntry.cc) [C:\Users\nikla\Desktop\DEV\test\node_modules\libui-nod
e\build\nbind.vcxproj]
  UiGrid.cc
C:\Users\nikla\.node-gyp\10.2.0\include\node\node.h(53): fatal error C1083: Cannot open include file: 'core.h': No such file or directory (compiling source file ..\src\EventLoop.cc) [C:\Users\nikla\Desktop\DEV\test\node_modules\libui-n
ode\build\nbind.vcxproj]
  UiGroup.cc
C:\Users\nikla\.node-gyp\10.2.0\include\node\node.h(53): fatal error C1083: Cannot open include file: 'core.h': No such file or directory (compiling source file ..\src\UiFontButton.cc) [C:\Users\nikla\Desktop\DEV\test\node_modules\libu
i-node\build\nbind.vcxproj]
  UiLabel.cc
C:\Users\nikla\.node-gyp\10.2.0\include\node\node.h(53): fatal error C1083: Cannot open include file: 'core.h': No such file or directory (compiling source file ..\src\UiForm.cc) [C:\Users\nikla\Desktop\DEV\test\node_modules\libui-node
\build\nbind.vcxproj]
  UiMenu.cc
C:\Users\nikla\.node-gyp\10.2.0\include\node\node.h(53): fatal error C1083: Cannot open include file: 'core.h': No such file or directory (compiling source file ..\src\UiGrid.cc) [C:\Users\nikla\Desktop\DEV\test\node_modules\libui-node
\build\nbind.vcxproj]
  UiMultilineEntry.cc
C:\Users\nikla\.node-gyp\10.2.0\include\node\node.h(53): fatal error C1083: Cannot open include file: 'core.h': No such file or directory (compiling source file ..\src\UiGroup.cc) [C:\Users\nikla\Desktop\DEV\test\node_modules\libui-nod
e\build\nbind.vcxproj]
  UiProgressBar.cc
C:\Users\nikla\.node-gyp\10.2.0\include\node\node.h(53): fatal error C1083: Cannot open include file: 'core.h': No such file or directory (compiling source file ..\src\UiLabel.cc) [C:\Users\nikla\Desktop\DEV\test\node_modules\libui-nod
e\build\nbind.vcxproj]
  UiRadioButtons.cc
C:\Users\nikla\.node-gyp\10.2.0\include\node\node.h(53): fatal error C1083: Cannot open include file: 'core.h': No such file or directory (compiling source file ..\src\UiMenu.cc) [C:\Users\nikla\Desktop\DEV\test\node_modules\libui-node
\build\nbind.vcxproj]
  UiSeparator.cc
C:\Users\nikla\.node-gyp\10.2.0\include\node\node.h(53): fatal error C1083: Cannot open include file: 'core.h': No such file or directory (compiling source file ..\src\UiMultilineEntry.cc) [C:\Users\nikla\Desktop\DEV\test\node_modules\
libui-node\build\nbind.vcxproj]
  UiSlider.cc
C:\Users\nikla\.node-gyp\10.2.0\include\node\node.h(53): fatal error C1083: Cannot open include file: 'core.h': No such file or directory (compiling source file ..\src\UiProgressBar.cc) [C:\Users\nikla\Desktop\DEV\test\node_modules\lib
ui-node\build\nbind.vcxproj]
  UiSpinbox.cc
C:\Users\nikla\.node-gyp\10.2.0\include\node\node.h(53): fatal error C1083: Cannot open include file: 'core.h': No such file or directory (compiling source file ..\src\UiRadioButtons.cc) [C:\Users\nikla\Desktop\DEV\test\node_modules\li
bui-node\build\nbind.vcxproj]
  UiTab.cc
C:\Users\nikla\.node-gyp\10.2.0\include\node\node.h(53): fatal error C1083: Cannot open include file: 'core.h': No such file or directory (compiling source file ..\src\UiSeparator.cc) [C:\Users\nikla\Desktop\DEV\test\node_modules\libui
-node\build\nbind.vcxproj]
  UiWindow.cc
C:\Users\nikla\.node-gyp\10.2.0\include\node\node.h(53): fatal error C1083: Cannot open include file: 'core.h': No such file or directory (compiling source file ..\src\UiSlider.cc) [C:\Users\nikla\Desktop\DEV\test\node_modules\libui-no
de\build\nbind.vcxproj]
  AttributedString.cc
C:\Users\nikla\.node-gyp\10.2.0\include\node\node.h(53): fatal error C1083: Cannot open include file: 'core.h': No such file or directory (compiling source file ..\src\UiSpinbox.cc) [C:\Users\nikla\Desktop\DEV\test\node_modules\libui-n
ode\build\nbind.vcxproj]
  FontAttribute.cc
C:\Users\nikla\.node-gyp\10.2.0\include\node\node.h(53): fatal error C1083: Cannot open include file: 'core.h': No such file or directory (compiling source file ..\src\UiTab.cc) [C:\Users\nikla\Desktop\DEV\test\node_modules\libui-node\
build\nbind.vcxproj]
  FontDescriptor.cc
C:\Users\nikla\.node-gyp\10.2.0\include\node\node.h(53): fatal error C1083: Cannot open include file: 'core.h': No such file or directory (compiling source file ..\src\UiWindow.cc) [C:\Users\nikla\Desktop\DEV\test\node_modules\libui-no
de\build\nbind.vcxproj]
  OpenTypeFeatures.cc
C:\Users\nikla\.node-gyp\10.2.0\include\node\node.h(53): fatal error C1083: Cannot open include file: 'core.h': No such file or directory (compiling source file ..\src\Font\AttributedString.cc) [C:\Users\nikla\Desktop\DEV\test\node_mod
ules\libui-node\build\nbind.vcxproj]
  BrushGradientStop.cc
C:\Users\nikla\.node-gyp\10.2.0\include\node\node.h(53): fatal error C1083: Cannot open include file: 'core.h': No such file or directory (compiling source file ..\src\Font\FontAttribute.cc) [C:\Users\nikla\Desktop\DEV\test\node_module
s\libui-node\build\nbind.vcxproj]
  DrawBrush.cc
C:\Users\nikla\.node-gyp\10.2.0\include\node\node.h(53): fatal error C1083: Cannot open include file: 'core.h': No such file or directory (compiling source file ..\src\Font\FontDescriptor.cc) [C:\Users\nikla\Desktop\DEV\test\node_modul
es\libui-node\build\nbind.vcxproj]
  DrawMatrix.cc
C:\Users\nikla\.node-gyp\10.2.0\include\node\node.h(53): fatal error C1083: Cannot open include file: 'core.h': No such file or directory (compiling source file ..\src\Font\OpenTypeFeatures.cc) [C:\Users\nikla\Desktop\DEV\test\node_mod
ules\libui-node\build\nbind.vcxproj]
  DrawStrokeParams.cc
C:\Users\nikla\.node-gyp\10.2.0\include\node\node.h(53): fatal error C1083: Cannot open include file: 'core.h': No such file or directory (compiling source file ..\src\UiArea\BrushGradientStop.cc) [C:\Users\nikla\Desktop\DEV\test\node_
modules\libui-node\build\nbind.vcxproj]
  DrawTextLayout.cc
C:\Users\nikla\.node-gyp\10.2.0\include\node\node.h(53): fatal error C1083: Cannot open include file: 'core.h': No such file or directory (compiling source file ..\src\UiArea\DrawBrush.cc) [C:\Users\nikla\Desktop\DEV\test\node_modules\
libui-node\build\nbind.vcxproj]
  UiArea.cc
C:\Users\nikla\.node-gyp\10.2.0\include\node\node.h(53): fatal error C1083: Cannot open include file: 'core.h': No such file or directory (compiling source file ..\src\UiArea\DrawMatrix.cc) [C:\Users\nikla\Desktop\DEV\test\node_modules
\libui-node\build\nbind.vcxproj]
  UiAreaDrawParams.cc
C:\Users\nikla\.node-gyp\10.2.0\include\node\node.h(53): fatal error C1083: Cannot open include file: 'core.h': No such file or directory (compiling source file ..\src\UiArea\DrawStrokeParams.cc) [C:\Users\nikla\Desktop\DEV\test\node_m
odules\libui-node\build\nbind.vcxproj]
  UiAreaHandler.cc
C:\Users\nikla\.node-gyp\10.2.0\include\node\node.h(53): fatal error C1083: Cannot open include file: 'core.h': No such file or directory (compiling source file ..\src\UiArea\DrawTextLayout.cc) [C:\Users\nikla\Desktop\DEV\test\node_mod
ules\libui-node\build\nbind.vcxproj]
  UiAreaKeyEvent.cc
C:\Users\nikla\.node-gyp\10.2.0\include\node\node.h(53): fatal error C1083: Cannot open include file: 'core.h': No such file or directory (compiling source file ..\src\UiArea\UiArea.cc) [C:\Users\nikla\Desktop\DEV\test\node_modules\lib
ui-node\build\nbind.vcxproj]
  UiAreaMouseEvent.cc
C:\Users\nikla\.node-gyp\10.2.0\include\node\node.h(53): fatal error C1083: Cannot open include file: 'core.h': No such file or directory (compiling source file ..\src\UiArea\UiAreaDrawParams.cc) [C:\Users\nikla\Desktop\DEV\test\node_m
odules\libui-node\build\nbind.vcxproj]
  UiDrawContext.cc
C:\Users\nikla\.node-gyp\10.2.0\include\node\node.h(53): fatal error C1083: Cannot open include file: 'core.h': No such file or directory (compiling source file ..\src\UiArea\UiAreaHandler.cc) [C:\Users\nikla\Desktop\DEV\test\node_modu
les\libui-node\build\nbind.vcxproj]
  UiDrawPath.cc
C:\Users\nikla\.node-gyp\10.2.0\include\node\node.h(53): fatal error C1083: Cannot open include file: 'core.h': No such file or directory (compiling source file ..\src\UiArea\UiAreaKeyEvent.cc) [C:\Users\nikla\Desktop\DEV\test\node_mod
ules\libui-node\build\nbind.vcxproj]
  libui_loop.cc
C:\Users\nikla\.node-gyp\10.2.0\include\node\node.h(53): fatal error C1083: Cannot open include file: 'core.h': No such file or directory (compiling source file ..\src\UiArea\UiDrawContext.cc) [C:\Users\nikla\Desktop\DEV\test\node_modu
les\libui-node\build\nbind.vcxproj]
C:\Users\nikla\.node-gyp\10.2.0\include\node\node.h(53): fatal error C1083: Cannot open include file: 'core.h': No such file or directory (compiling source file ..\src\UiArea\UiAreaMouseEvent.cc) [C:\Users\nikla\Desktop\DEV\test\node_m
odules\libui-node\build\nbind.vcxproj]
  timer.cc
  Buffer.cc
C:\Users\nikla\.node-gyp\10.2.0\include\node\node.h(53): fatal error C1083: Cannot open include file: 'core.h': No such file or directory (compiling source file ..\src\UiArea\UiDrawPath.cc) [C:\Users\nikla\Desktop\DEV\test\node_modules
\libui-node\build\nbind.vcxproj]
  Binding.cc
C:\Users\nikla\.node-gyp\10.2.0\include\node\node.h(53): fatal error C1083: Cannot open include file: 'core.h': No such file or directory (compiling source file ..\src\arch\win32\timer.cc) [C:\Users\nikla\Desktop\DEV\test\node_modules\
libui-node\build\nbind.vcxproj]
C:\Users\nikla\.node-gyp\10.2.0\include\node\node.h(53): fatal error C1083: Cannot open include file: 'core.h': No such file or directory (compiling source file ..\..\nbind\src\v8\Buffer.cc) [C:\Users\nikla\Desktop\DEV\test\node_module
s\libui-node\build\nbind.vcxproj]
  win_delay_load_hook.cc
C:\Users\nikla\.node-gyp\10.2.0\include\node\node.h(53): fatal error C1083: Cannot open include file: 'core.h': No such file or directory (compiling source file ..\..\nbind\src\v8\Binding.cc) [C:\Users\nikla\Desktop\DEV\test\node_modul
es\libui-node\build\nbind.vcxproj]
C:\Users\nikla\.node-gyp\10.2.0\include\node\node.h(53): fatal error C1083: Cannot open include file: 'core.h': No such file or directory (compiling source file ..\src\arch\win32\libui_loop.cc) [C:\Users\nikla\Desktop\DEV\test\node_mod
ules\libui-node\build\nbind.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\nikla\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\nikla\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "build"
gyp ERR! cwd C:\Users\nikla\Desktop\DEV\test\node_modules\libui-node
gyp ERR! node -v v10.2.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! libui-node@0.2.0 build: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the libui-node@0.2.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\nikla\AppData\Roaming\npm-cache\_logs\2018-05-24T11_31_31_002Z-debug.log
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! libui-node@0.2.0 install: `libui-download && autogypi && npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the libui-node@0.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\nikla\AppData\Roaming\npm-cache\_logs\2018-05-24T11_31_31_965Z-debug.log
</pre></code>
</details>

**Comment by mischnic** [comment]
Caused by Node 10.2.0: https://github.com/nodejs/node/issues/20921

**Comment by parro-it** [comment]
It's not related to Windows 10, I can reproduce in High Sierra.

**Comment by parro-it** [comment]
> Caused by Node 10.2.0: nodejs/node#20921

👍🏻
