### ISSUE TITLE
UiHorizontalSeparator goes vertical on too small of a screen

### ISSUE THREAD

**Issue by Prefinem** [parro-it/libui-node#122]
![screen shot 2018-07-22 at 4 52 20 pm](https://user-images.githubusercontent.com/2748262/43050531-c6ed8d26-8dcf-11e8-8d96-73e8039d6c36.png)
![screen shot 2018-07-22 at 4 52 27 pm](https://user-images.githubusercontent.com/2748262/43050532-c8b57d12-8dcf-11e8-9658-624e423fa15f.png)

I assume it's an issue of libui but I wanted to raise it here first just in case.

**Comment by mischnic** [comment]
Could you post the corresponding code?

**Comment by Prefinem** [comment]
Here is the relevant code

```javascript
const libui = require('libui-node');

const mainBox = new libui.UiVerticalBox();
const statusBox = new libui.UiHorizontalBox();
const statusDivider = new libui.UiHorizontalSeparator();
const statusLabel = new libui.UiLabel('Status: Stopped');
const statusButton = new libui.UiButton('Start');

statusBox.append(statusLabel, 1);
statusBox.append(statusDivider, 1);
statusBox.append(statusButton, 1);

mainBox.padded = true;
mainBox.append(statusBox, 1);
```

**Comment by mischnic** [comment]
The problem seems to be that `statusbox` is a horizontal box. Changing it to a vertical box makes the seperator work.
It also happens with this libui code (so you might want to go ahead an open a libui issue - by the way, the code behaves the same on linux/gtk):
```c
#include <stdio.h>
#include <string.h>
#include "ui.h"

int main(void)
{
	uiInitOptions o;
	const char *err;

	memset(&o, 0, sizeof (uiInitOptions));
	err = uiInit(&o);
	if (err != NULL) {
		fprintf(stderr, "error initializing ui: %s\n", err);
		uiFreeInitError(err);
		return 1;
	}

	uiWindow *mainwin = uiNewWindow("test", 400, 400, 1);
	uiWindowSetMargined(mainwin, 1);

	uiBox *box = uiNewHorizontalBox();
	// uiBox *box = uiNewVerticalBox();
	uiBoxSetPadded(box, 1);
	uiWindowSetChild(mainwin, uiControl(box));

	uiLabel *label = uiNewLabel("Status: Stopped");
	uiBoxAppend(box, uiControl(label), 0);
	uiSeparator *sep = uiNewHorizontalSeparator();
	uiBoxAppend(box, uiControl(sep), 0);
	uiButton *but = uiNewButton("Start");
	uiBoxAppend(box, uiControl(but), 0);

	uiControlShow(uiControl(mainwin));

	uiMain();
	return 0;
}
```

horizontal box:

![bildschirmfoto 2018-07-23 um 11 25 56](https://user-images.githubusercontent.com/4586894/43068649-58eb030c-8e6b-11e8-8fc2-3db472a1a780.png)

vertical box:
![bildschirmfoto 2018-07-23 um 11 26 03](https://user-images.githubusercontent.com/4586894/43068650-590f6800-8e6b-11e8-9c65-8cffd7f464e0.png)

**Comment by Prefinem** [comment]
Wow, so, yes, I meant that the UiHorizontalSeparator is not vertical.  My assumption was that since UiHorizontalBox laid things horizontally, that the UiHorizontalSeparator was the separator that you would use for a UiHorizontalBox.

That being said, with a UiHorizontalBox, the issue happens with both UiHorizontalSeparator and UiVerticalSeparator.

Here is the code I am using to test both of them.

```javascript
const libui = require('libui-node');

const menu = new libui.UiMenu('');

menu.appendQuitItem();
menu.appendAboutItem();

const win = new libui.UiWindow('Sample', 0, 0, false);
const mainBox = new libui.UiVerticalBox();
const statusBox = new libui.UiHorizontalBox();
// const statusDivider = new libui.UiHorizontalSeparator();
// or
// const statusDivider = new libui.UiVerticalSeparator();
const statusLabel = new libui.UiLabel('Status: Stopped');
const statusButton = new libui.UiButton('Start');

statusBox.append(statusLabel, 1);
statusBox.append(statusDivider, 1);
statusBox.append(statusButton, 1);

mainBox.padded = true;
mainBox.append(statusBox, 1);

libui.onShouldQuit(() => {
	win.close();
	libui.stopLoop();
});
win.margined = 1;
win.onClosing(() => {
	libui.stopLoop();
});
win.setChild(mainBox);
win.show();
libui.startLoop();

```

Which gives the same result.

 I do think it has something to do with the aspect ration, but that is not what I would expect to happen.  I will raise an issue with the libui repo.

Thanks for the feedback
