### ISSUE TITLE
Common methods to handle children

### ISSUE THREAD

**Issue by PaulBGD** [parro-it/libui-node#20]
Currently children are a bit weird. There's setChild and append, which belong to different UI items. I'm suggesting common methods called setChildren, addChild, appendChild, and removeChild that belongs in Window, Group, RadioButtions, Vertical/Horizontal Box, and others.

setChildren would accept an array of children, overwriting any current children. For UI items like Window/Group that only accept one child, it would throw an error if there's more than one child in the array.

addChild would basically do what append does. For UI items like Window/Group this would throw an error if it already has a child.

appendChild would accept a child and an index. Pushes children after it to a higher index. For UI items like Window/Group this would throw an error if it already has a child.

removeChild would remove a child at the specified index. Index defaults to 0. For UI items like Window/Group this would throw an error if the index is not 0.

Any thoughts? After working with this library for a few hours it seems like there's currently too many ways to handle children and this is just one suggestion for unifying them.

**Comment by parro-it** [comment]
There some discussion on container widget [here](https://github.com/andlabs/libui/issues/120)
You may want to continue the discussion there...
My thoughts:

* setChildren - this could be really useful!
* appendChild - I would expect a function with this name always insert at enfd of a container. Some widget already at an `insertAt` function. I think this is a better name.
* removeChild - I would implement this only on multi-childdren widget. For single child container I would remove with setChild(null) or similar...

Also, I would keep setChild function name for window and group. This name make it clear that they accept only one child.

**Comment by PaulBGD** [comment]
Yeah I was thinking about `insertAt`, but some components already use it.
As for window/group, I suppose it makes sense.

**Comment by PaulBGD** [comment]
The issue at libui seems to be handling the issue, I'll close this.
