### ISSUE TITLE
Find a way to run an app without setting LD_LIBRARY_PATH on linux

### ISSUE THREAD

**Issue by PaulBGD** [parro-it/libui-node#22]
Whenever I run libui-node it throws an error:

```
module.js:568
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: libui.so.0: cannot open shared object file: No such file or directory
    at Error (native)
    at Object.Module._extensions..node (module.js:568:18)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
```

My directory structure looks like:

```
libui-node/
   examples/
      core-api.js
   libui/
     build/
        libui.so
        libui.so.0
```

I can't run any of the examples without copying the libui.so* files to my library folder. I had no errors with compiling. Ubuntu Linux 16.04

**Comment by PaulBGD** [comment]
My bad, didn't realize I had to set LD_LIBRARY_PATH.

**Comment by parro-it** [comment]
I reopened and renamed this issue because I want to avoid the LD_LIBRARY_PATH stuff, seems weirds...

**Comment by parro-it** [comment]
Please try to switch to `removed-ld-library` branch and rebuild. You should be able to run tests and example without setting LD_LIBRARY_PATH

**Comment by PaulBGD** [comment]
Looks good 👍

**Comment by PaulBGD** [comment]
I tested the fix on mac, works great as well.

**Comment by parro-it** [comment]
Thank you, I just tested on Linux and it's working, I'm going to merge the branch and close this issue...
