### ISSUE TITLE
Monitors and Size

### ISSUE THREAD

**Issue by PaulBGD** [parro-it/libui-node#40]
Node lacks a lot of tools for getting information about the screen, so there's a few things I think would work great with libui-node:
- Monitors: getting the amount of monitors and their individual sizes
- Size: get width/height of screen

**Comment by forivall** [comment]
If these aren't things that are part of libui, and you can't find any existing libraries to do this, you should submit this to https://github.com/sindresorhus/module-requests/

**Comment by parro-it** [comment]
Robotjs has a method to get screen size, and it is multiplatform.
https://github.com/octalmage/robotjs/blob/master/src/robotjs.cc#L682
I think it could be possible to extract from there the pieces we need.

A screen tool is definitely useful!

**Comment by parro-it** [comment]
Seems to be implemented [in screen.c file](https://github.com/octalmage/robotjs/blob/master/src/screen.c)

**Comment by PaulBGD** [comment]
@forivall I get that it's not part of libui, but when using libui you can actually use code to retrieve this information. There's no way to get screen information in JavaScript.

**Comment by parro-it** [comment]
Just published it: https://github.com/parro-it/screen-info
