### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by parro-it** [parro-it/libui-node#43]
I just merged Windows branch into master. 

From now on, libui-node support Windows OS too!

After many attempts using various methods, I finally implemented the event loop using a simple libuv timer.

Linux and macOS got a better event loop implementation, with a background blocking thread that check for any pending GUI event and when there are one or more, it run a callback in main js thread that dispatch all events.

It appear that on Windows we have no way to check for the presence of pending events on other threads, so I revert to checking them in main thread, once every 100 ms. 

Anyway, CPU usage appear to be lower than 1% on my machine. So at least by now, I choose to go on with this implementation. Maybe we can find a better way in future.

Please test it and report any issue you'll find, thanks!

**Comment by tracker1** [comment]
You should run updates every 16ms to hit 60fps...

**Comment by PaulBGD** [comment]
Or rather, run them to match the screen's refresh rate.

**Comment by PaulBGD** [comment]
Yeah after running the examples, you can definitely feel the lag on a 60hz monitor. I can't imagine how a 144hz monitor would feel.

**Comment by parro-it** [comment]
Ok, thank you, I will shorten the timeout to 16ms.

**Comment by parro-it** [comment]
Event loop is completely implemented on 0.1.0 and should be more performant on Windows.
