### ISSUE TITLE
UIArea - handler methods not invoked (Windows10)

### ISSUE THREAD

**Issue by goessner** [parro-it/libui-node#45]
I succeeded to get your UIArea example up and running in my Windows Environment.

Unfortunately there is no rectangle. Inserting some "console.log's I can see, that neither the 'draw'- nor the 'mouseEvent' method of the handeler object is invoked.

Would love to work with that cool piece.

**Comment by goessner** [comment]
ok .. now I was able to reduce it to the following working code ... it works great.
``` javascript
var libui = require('../index.js');

libui.Ui.init();

function draw(area, p) {
   var brush = new libui.DrawBrush(),
       path = new libui.UiDrawPath(0);

   brush.setColor(new libui.Color(128,0,0,1));
   path.addRectangle(50, 30, 250, 120);
   path.end();
   p.getContext().fill(path, brush);
   path.freePath();
}

var win = new libui.UiWindow('minimal Canvas rectangle', 640, 480, true),
    canvas = new libui.UiArea(draw,null,null,null,null,300,150);

win.setChild(canvas);

win.onClosing(function () {
    win.close();
    libui.stopLoop();
});

win.show();

libui.startLoop();
```

**Comment by parro-it** [comment]
Thank you @goessner, I add your code to the documentation instead of the first version of the code.
