### ISSUE TITLE
Error: The specified module could not be found.

### ISSUE THREAD

**Issue by kraxarn** [parro-it/libui-node#46]
Tried running the control-gallery example on OS X which works without issues, but attempting to run it on Windows 7 results in an error:

```
module.js:568
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: The specified module could not be found.
\\?\node_modules\libui-node\build\Release\nbind.node
    at Error (native)
    at Object.Module._extensions..node (module.js:568:18)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at initNode (node_modules\libui-node\node_modules\nind\dist\nbind.js:162:15)
    at node_modules\libui-node\node_modules\nbind\dist\bind.js:130:13
    at findCompiledModule (node_modules\libui-node\nodemodules\nbind\dist\nbind.js:94:13)
```

EDIT: Found the problem. It's having issues finding libui.dll and copying the file from node_modules/libui-node to the root of the script fixed it and it now works fine. Don't know if there's any better solution to this...

**Comment by parro-it** [comment]
Hi @KraXarN, thank you for the report. 
You got some kind of error during the copy process of the dll?

Where exactly did you place the dll to make it work? 

It should work from node_modules/libui-node, if it doesn't it means there is some problem on the loading phase on Windows.

**Comment by KraXarN** [comment]
Hello. Sorry for the long delay, forgot to reply. :/

[Here](http://pastebin.com/14eX7MmV)'s the full log of the install. I can't find any information of it copying the dll file, so maybe that's the issue.

If the folder where the script is I'm trying to run, containing my code is the root, the dll was placed in `/node_modules/libui-node/libui.dll` and I had to copy it to `/libui.dll` for it to work. If the dll isn't in that location and in the node_modules folder, that errors pops up upon starting my script.

**Comment by sculley4** [comment]
I had this exact problem as well. Windows 10 Pro v1607. Node v6.6.0. Npm v 3.10.8 

I was banging my head against this for a while until I found this issue. Any ideas why this is happening?

**Comment by KraXarN** [comment]
Just go with my solution for now :p

**Comment by szkrd** [comment]
Same here, Windows 8.1. The copy dll did the trick, thanks @KraXarN !

**Comment by int0h** [comment]
I have the same issue :( . What I did:
- clone repo
- run `npm -S i`
- npm start

```
...
module.js:598
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: The specified module could not be found.
\\?\C:\cygwin64\home\user\libui-node\nbind.node
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:488:32)
  ...
```
But in my case there are both `nbind.node` and `libui.dll` in `cwd`.

- Windows 8.1
- node 7.5.0
- npm 4.1.2

Could you upload somewhere prebuilt demo that can be run out of the box.

**Comment by buckle2000** [comment]
Same here

`nbind.node` isn't copied to `node_modules/libui-node/`

**Comment by parro-it** [comment]
Next version (that will be coming next weeks) will solve the problem.
In the meanwhile, @kusti8 solve it to use it in proton-native here: https://github.com/kusti8/libui-node/blob/master/copy_node.js

**Comment by mischnic** [comment]
> nbind.node isn't copied to node_modules/libui-node/

now it is (#62)

**Comment by nomisx** [comment]
When installing libui-node on Mac OS there was an error. 
Error: Could not locate the bindings file. Tried:
/usr/local/bin/libui-node/nbind.node

solution

sudo cp /usr/local/bin/node_modules/libui-node/nbind.node /usr/local/bin/libui-node/nbind.node

Now you can run the examples in examples
$ node /examples/grid.js

Simon
