### ISSUE TITLE
`menu` doesn't work on OS X El Capitan

### ISSUE THREAD

**Issue by lukechilds** [parro-it/libui-node#52]
I don't get any menu items other than "node" when I run any of the examples.

**Comment by parro-it** [comment]
What OS are you using? 
libui does not have great support for menu at the moment. See this [issue there](https://github.com/andlabs/libui/issues/152)

**Comment by lukechilds** [comment]
Also macOS

**Comment by mischnic** [comment]
Also regarding the menu: is #4 preventing the `Quit` menu action (and also CMD+Q) from working?

**Comment by parro-it** [comment]
Seems to work in new upcoming version. @lukechilds could you check if you still have the problem on branch 0_1_0?

**Comment by parro-it** [comment]
Version 0.1.0 is on npm, should fix this problem. @lukechilds reopen the issue if needed.

**Comment by lukechilds** [comment]
Thanks, I'm really busy with other work at the moment but can't wait to find some time to have a play with this!
