### ISSUE TITLE
implement NSOpenPanel or other native ui

### ISSUE THREAD

**Issue by RockyF** [parro-it/libui-node#68]
like title.
I wish it could implement NSOpenPanel on macOS, or other component on Windows...

**Comment by parro-it** [comment]
This project only implements node binding to [libui](https://github.com/andlabs/libui) library. You should ask for this kind of stuff there

**Comment by mischnic** [comment]
https://github.com/parro-it/libui-node/blob/340b763023616ce23234d25a7fa69da4493b4943/examples/node-pad.js#L37

This will open a native dialog (NSOpenPanel on macOS, implementation https://github.com/andlabs/libui/blob/86c4485578d6d58aff6528b27558bc1ccc6aadbe/darwin/stddialogs.m#L35).

Is this what you meant?

**Comment by mischnic** [comment]
@parro-it There is no libui-node documentation for the dialogs!

**Comment by parro-it** [comment]
Thank you @mischnic . Sorry for my bad advice @RockyF !

**Comment by parro-it** [comment]
You can find how to use the open dialog on this example:
https://github.com/parro-it/libui-node/blob/master/examples/control-gallery.js#L120

**Comment by RockyF** [comment]
I was too careless. I didn't see it. Thank you.

`const filename = libui.UiDialogs.openFile(win);`
