### ISSUE TITLE
Implement libui's text formatting

### ISSUE THREAD

**Issue by mischnic** [parro-it/libui-node#70]
- Might take some work
- Maybe wait a bit in case there are api changes?

Example: https://github.com/andlabs/libui/blob/master/examples/drawtext/main.c

**Comment by parro-it** [comment]
I looked at the example, very nice! And very useful too.

The API is really large, I think we should develop it on separate branch, and continue on master with bug-fixing or other minor improvement. 

First step is to prepare a new release on my libui fork. We'll use this new release on text branch, and continue to use the current one on master.

**Comment by parro-it** [comment]
Also, maybe we need to change how string property are handled, because of the new UTF decoding introduced in libui

**Comment by mischnic** [comment]
I already started with the header: https://github.com/parro-it/libui-node/tree/font
