### ISSUE TITLE
Automate source code listing in binding.gyp

### ISSUE THREAD

**Issue by parro-it** [parro-it/libui-node#73]
While spelunking [yoga](https://github.com/facebook/yoga) source code, I found I nice way to avoid listing every source file in binding.gyp:

[`<!@(ls -1 sources/yoga/*.cpp)`](https://github.com/facebook/yoga/blob/master/javascript/binding.gyp#L9)

I think we could simplify the file using the same command, but I have to study which command on windows replace `ls -1`

**Comment by mischnic** [comment]
unix/mac:
```
"<!@(ls -1 src/*.cc)",
"<!@(ls -1 src/UiArea/*.cc)"
```

win:
```
"<!@(dir /B src/*.cc)",
"<!@(dir /B src/UiArea/*.cc)"
```

(not tested in the actual binding.gyp file)

**Comment by parro-it** [comment]
Works on linux too!

**Comment by parro-it** [comment]
But (obviouslly) not on Windows :-1: dir /B does not include relative path.
Anyway, I wrote  a small node module to do the same listing: list-sources.js
Using that works fine...
