### ISSUE TITLE
Complete UiArea

### ISSUE THREAD

**Issue by mischnic** [parro-it/libui-node#77]
- [x] Documentation (#69)
- [x] More enums: https://github.com/andlabs/libui/blob/51f72abba84e3941deba1c8f699046a48d1f7fb9/ui.h#L356-L383)
  - [x] uiDrawBrushType
  - [x] uiDrawLineCap
  - [x] uiDrawLineJoin
  - [x] uiDrawFillMode

- [x] Modifiers, uiExtKey https://github.com/andlabs/libui/blob/d53ab65589e126bb9bf40c99d67ca1d94bbff738/ui.h#L997

- [x] DrawStrokeParams: Dashed
- [x] Gradient
  - [x] fix `std::vector<BrushGradientStop> DrawBrush::getStops`
- [x] this isn't exposed to JS: https://github.com/parro-it/libui-node/blob/ae067f5c79f1ac85e593dfc1e1684275ee27d96a/src/UiArea/UiAreaMouseEvent.cc#L29-L31
- [x] `b` is never freed: https://github.com/parro-it/libui-node/blob/36c278f9453d9ec9750bb91cc1b5fb1d400877ff/src/UiArea/DrawBrush.cc#L7
- [x] `sp` is never freed: https://github.com/parro-it/libui-node/blob/36c278f9453d9ec9750bb91cc1b5fb1d400877ff/src/UiArea/DrawStrokeParams.cc#L8

- [x] leak: https://github.com/parro-it/libui-node/blob/445e3952988a55c5486a9aff3cdd7d49a7dd0080/src/UiArea/UiAreaKeyEvent.cc#L10-L15

**Comment by mischnic** [comment]
Work started on branch [area_fixes](https://github.com/parro-it/libui-node/tree/area_fixes).

**Comment by parro-it** [comment]
Awesome! I'll merge it in 0_2_0 tonight
