### ISSUE TITLE
Add searchEntry and passwordEntry to control gallery example

### ISSUE THREAD

**Issue by parro-it** [parro-it/libui-node#9]

**Comment by jjrv** [comment]
For some reason searchEntry doesn't work on OS X 10.8. Maybe you could check `os.platform()` and `os.release()` from `require('os')` and leave that control out if platform is `darwin` and release is `12.6.0` or earlier (not sure what's the exact cutoff point, that version doesn't support searchEntry but I don't know the first one that does)

**Comment by parro-it** [comment]
Today I tried on 10.10 and searchEntry was working... Anyway I'll do the version check you suggested.

**Comment by parro-it** [comment]
I removed searchEntry at all from darwin platform. I opened [an issue on libui repo](https://github.com/andlabs/libui/issues/132)
