### ISSUE TITLE
Cannot install on Ubuntu 17.10, missing xproto

### ISSUE THREAD

**Issue by njlr** [parro-it/libui-node#95]
I get the following error on Ubuntu 17.10: 

> node-gyp configure build
> 
> Package xproto was not found in the pkg-config search path.
> Perhaps you should add the directory containing `xproto.pc'
> to the PKG_CONFIG_PATH environment variable
> Package 'xproto', required by 'xau', not found
> gyp: Call to 'pkg-config gtk+-3.0 --cflags-only-I | sed s/-I//g' returned exit status 0 while in binding.gyp. while trying to load binding.gyp

I have GTK: 

> $ pkg-config --modversion gtk+-3.0
> 3.22.25

**Comment by njlr** [comment]
My `PKG_CONFIG_PATH` was wrong: 

```bash=
export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/lib/x86_64-linux-gnu/pkgconfig
export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/share/pkgconfig
```

**Comment by lucawen** [comment]
> My `PKG_CONFIG_PATH` was wrong:
> 
> ```
> export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/lib/x86_64-linux-gnu/pkgconfig
> export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/share/pkgconfig
> ```

This solve too many different problens that i have, like not found gtk+3 on cmake of opencv! But thats it :)
