### ISSUE TITLE
TextArea.getText() line ending discrepancy on Windows

### ISSUE THREAD

**Issue by mischnic** [parro-it/libui-node#97]
![bildschirmfoto 2018-04-28 um 22 14 48](https://user-images.githubusercontent.com/4586894/39400495-a859fcc2-4b31-11e8-8143-6ec227ac94fb.png)
(from here: https://github.com/parro-it/libui-node/pull/84#discussion_r184168212)

**Comment by parro-it** [comment]
I think we could solve the issue by replacing newlines in `setText`

**Comment by mischnic** [comment]
> It's also interesting that textarea.getText() returns the text with "\n" (also on windows), but setText() requires the platform specific type.

@andlabs Is this the intended behavior?

**Comment by andlabs** [comment]
That means there is a bug in utf16.cpp `CRLFtoLF()`. Will investigate later; please file this on libui.

**Comment by parro-it** [comment]
The bug was discovered by @mimecorg and should be already fixed now in libui master
